import { useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { DashboardAno } from '@/types/dashboard'

export function PorAnoChart({ anos }: { anos: DashboardAno[] }) {
  const [modo, setModo] = useState<'jogos' | 'horas'>('jogos')
  if (!anos.length) return null
  const dados = anos.map((item) => ({ ...item, valor: modo === 'jogos' ? item.total_jogos : Math.round(item.total_segundos / 3600) }))
  return <section aria-label="Por Ano" className="space-y-4 rounded-[10px] border border-[var(--border)] bg-[var(--bg-surface)] p-4"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-[var(--text-primary)]">Por Ano</h2><div className="flex rounded border border-[var(--border-subtle)] text-[10px]"><button type="button" onClick={() => setModo('jogos')} className={`px-2 py-1 ${modo === 'jogos' ? 'bg-[var(--accent)] text-[var(--accent-foreground)]' : 'text-[var(--text-muted)]'}`}>Jogos</button><button type="button" onClick={() => setModo('horas')} className={`px-2 py-1 ${modo === 'horas' ? 'bg-[var(--accent)] text-[var(--accent-foreground)]' : 'text-[var(--text-muted)]'}`}>Horas</button></div></header><div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={dados} aria-label="Gráfico de jogos e horas por ano"><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="ano" stroke="var(--text-muted)" fontSize={11} /><YAxis stroke="var(--text-muted)" fontSize={11} allowDecimals={false} /><Tooltip contentStyle={{ background: 'var(--bg-surface-alt)', border: '1px solid var(--border)' }} formatter={(value) => [modo === 'jogos' ? value : `${value}h`, modo === 'jogos' ? 'Jogos' : 'Horas']} /><Bar dataKey="valor" radius={[4, 4, 0, 0]}>{dados.map((item) => <Cell key={item.ano} fill={item.ano === new Date().getFullYear() ? 'var(--highlight-gold)' : 'var(--accent)'} />)}</Bar></BarChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-[10px] text-[var(--text-muted)] sm:grid-cols-4">{anos.map((item) => <span key={item.ano}>{item.ano}: {item.game_do_ano?.nome ?? 'sem destaque'}</span>)}</div></section>
}
