// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listarEstatisticasPorAno = `-- name: ListarEstatisticasPorAno :many
WITH por_ano AS (
    SELECT
        EXTRACT(YEAR FROM j.finalizado_em)::int AS ano,
        COUNT(*)::bigint AS total_jogos,
        COALESCE(SUM(j.tempo_jogado), 0)::bigint AS total_segundos
    FROM jogos_zerados j
    WHERE j.usuario_id = $1 AND j.deleted_at IS NULL
    GROUP BY EXTRACT(YEAR FROM j.finalizado_em)::int
),
destaques AS (
    SELECT
        EXTRACT(YEAR FROM d.finalizado_em)::int AS ano,
        d.id,
        d.nome,
        d.console,
        COALESCE(d.igdb_capa_url, '')::text AS igdb_capa_url,
        d.nota
    FROM jogos_zerados d
    WHERE d.usuario_id = $1 AND d.deleted_at IS NULL AND d.destaque = true
)
SELECT
    pa.ano,
    pa.total_jogos,
    pa.total_segundos,
    d.id AS destaque_id,
    d.nome AS destaque_nome,
    d.console AS destaque_console,
    d.igdb_capa_url AS destaque_igdb_capa_url,
    d.nota AS destaque_nota
FROM por_ano pa
LEFT JOIN destaques d ON pa.ano = d.ano
ORDER BY pa.ano ASC
`

type ListarEstatisticasPorAnoRow struct {
	Ano                 int32
	TotalJogos          int64
	TotalSegundos       int64
	DestaqueID          pgtype.Int4
	DestaqueNome        pgtype.Text
	DestaqueConsole     pgtype.Text
	DestaqueIgdbCapaUrl pgtype.Text
	DestaqueNota        pgtype.Int4
}

func (q *Queries) ListarEstatisticasPorAno(ctx context.Context, usuarioID int32) ([]ListarEstatisticasPorAnoRow, error) {
	rows, err := q.db.Query(ctx, listarEstatisticasPorAno, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEstatisticasPorAnoRow
	for rows.Next() {
		var i ListarEstatisticasPorAnoRow
		if err := rows.Scan(
			&i.Ano,
			&i.TotalJogos,
			&i.TotalSegundos,
			&i.DestaqueID,
			&i.DestaqueNome,
			&i.DestaqueConsole,
			&i.DestaqueIgdbCapaUrl,
			&i.DestaqueNota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterBreakdownTipo = `-- name: ObterBreakdownTipo :many
SELECT
    tipo,
    COUNT(*)::bigint AS total_jogos
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND tipo IS NOT NULL
  AND tipo != ''
  AND genero IS NOT NULL
  AND unaccent(LOWER(genero)) = unaccent(LOWER($2::text))
GROUP BY tipo
ORDER BY total_jogos DESC, tipo ASC
`

type ObterBreakdownTipoParams struct {
	UsuarioID int32
	Genero    string
}

type ObterBreakdownTipoRow struct {
	Tipo       pgtype.Text
	TotalJogos int64
}

func (q *Queries) ObterBreakdownTipo(ctx context.Context, arg ObterBreakdownTipoParams) ([]ObterBreakdownTipoRow, error) {
	rows, err := q.db.Query(ctx, obterBreakdownTipo, arg.UsuarioID, arg.Genero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterBreakdownTipoRow
	for rows.Next() {
		var i ObterBreakdownTipoRow
		if err := rows.Scan(&i.Tipo, &i.TotalJogos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterDistribuicaoDificuldade = `-- name: ObterDistribuicaoDificuldade :many
SELECT
    dificuldade,
    COUNT(*)::bigint AS total_jogos
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND dificuldade IS NOT NULL
GROUP BY dificuldade
`

type ObterDistribuicaoDificuldadeRow struct {
	Dificuldade Dificuldade
	TotalJogos  int64
}

func (q *Queries) ObterDistribuicaoDificuldade(ctx context.Context, usuarioID int32) ([]ObterDistribuicaoDificuldadeRow, error) {
	rows, err := q.db.Query(ctx, obterDistribuicaoDificuldade, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterDistribuicaoDificuldadeRow
	for rows.Next() {
		var i ObterDistribuicaoDificuldadeRow
		if err := rows.Scan(&i.Dificuldade, &i.TotalJogos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterDistribuicaoNotas = `-- name: ObterDistribuicaoNotas :many
SELECT
    nota,
    COUNT(*)::bigint AS total
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND nota IS NOT NULL
GROUP BY nota
ORDER BY nota ASC
`

type ObterDistribuicaoNotasRow struct {
	Nota  int32
	Total int64
}

func (q *Queries) ObterDistribuicaoNotas(ctx context.Context, usuarioID int32) ([]ObterDistribuicaoNotasRow, error) {
	rows, err := q.db.Query(ctx, obterDistribuicaoNotas, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterDistribuicaoNotasRow
	for rows.Next() {
		var i ObterDistribuicaoNotasRow
		if err := rows.Scan(&i.Nota, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterRankingGeneros = `-- name: ObterRankingGeneros :many
SELECT
    genero,
    COUNT(*)::bigint AS total_jogos,
    COALESCE(SUM(tempo_jogado), 0)::bigint AS total_segundos
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND genero IS NOT NULL
  AND genero != ''
GROUP BY genero
ORDER BY total_jogos DESC, total_segundos DESC, genero ASC
`

type ObterRankingGenerosRow struct {
	Genero        pgtype.Text
	TotalJogos    int64
	TotalSegundos int64
}

func (q *Queries) ObterRankingGeneros(ctx context.Context, usuarioID int32) ([]ObterRankingGenerosRow, error) {
	rows, err := q.db.Query(ctx, obterRankingGeneros, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterRankingGenerosRow
	for rows.Next() {
		var i ObterRankingGenerosRow
		if err := rows.Scan(&i.Genero, &i.TotalJogos, &i.TotalSegundos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterRankingPlataformas = `-- name: ObterRankingPlataformas :many
SELECT
    console,
    COUNT(*)::bigint AS total_jogos,
    COALESCE(SUM(tempo_jogado), 0)::bigint AS total_segundos
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND console IS NOT NULL
  AND console != ''
GROUP BY console
ORDER BY total_jogos DESC, total_segundos DESC, console ASC
`

type ObterRankingPlataformasRow struct {
	Console       string
	TotalJogos    int64
	TotalSegundos int64
}

func (q *Queries) ObterRankingPlataformas(ctx context.Context, usuarioID int32) ([]ObterRankingPlataformasRow, error) {
	rows, err := q.db.Query(ctx, obterRankingPlataformas, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObterRankingPlataformasRow
	for rows.Next() {
		var i ObterRankingPlataformasRow
		if err := rows.Scan(&i.Console, &i.TotalJogos, &i.TotalSegundos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterRecordeMaisCurto = `-- name: ObterRecordeMaisCurto :one
SELECT
    id,
    nome,
    console,
    EXTRACT(YEAR FROM finalizado_em)::int AS ano,
    COALESCE(igdb_capa_url, '')::text AS igdb_capa_url,
    tempo_jogado AS tempo_jogado_segundos
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND tempo_jogado > 0
ORDER BY tempo_jogado ASC, finalizado_em DESC, id DESC
LIMIT 1
`

type ObterRecordeMaisCurtoRow struct {
	ID                  int32
	Nome                string
	Console             string
	Ano                 int32
	IgdbCapaUrl         string
	TempoJogadoSegundos int32
}

func (q *Queries) ObterRecordeMaisCurto(ctx context.Context, usuarioID int32) (ObterRecordeMaisCurtoRow, error) {
	row := q.db.QueryRow(ctx, obterRecordeMaisCurto, usuarioID)
	var i ObterRecordeMaisCurtoRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Console,
		&i.Ano,
		&i.IgdbCapaUrl,
		&i.TempoJogadoSegundos,
	)
	return i, err
}

const obterRecordeMaisLongo = `-- name: ObterRecordeMaisLongo :one
SELECT
    id,
    nome,
    console,
    EXTRACT(YEAR FROM finalizado_em)::int AS ano,
    COALESCE(igdb_capa_url, '')::text AS igdb_capa_url,
    tempo_jogado AS tempo_jogado_segundos
FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
ORDER BY tempo_jogado DESC, finalizado_em DESC, id DESC
LIMIT 1
`

type ObterRecordeMaisLongoRow struct {
	ID                  int32
	Nome                string
	Console             string
	Ano                 int32
	IgdbCapaUrl         string
	TempoJogadoSegundos int32
}

func (q *Queries) ObterRecordeMaisLongo(ctx context.Context, usuarioID int32) (ObterRecordeMaisLongoRow, error) {
	row := q.db.QueryRow(ctx, obterRecordeMaisLongo, usuarioID)
	var i ObterRecordeMaisLongoRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Console,
		&i.Ano,
		&i.IgdbCapaUrl,
		&i.TempoJogadoSegundos,
	)
	return i, err
}

const obterResumoDashboard = `-- name: ObterResumoDashboard :one
SELECT
    COUNT(*)::bigint AS total_jogos,
    COALESCE(SUM(tempo_jogado), 0)::bigint AS total_segundos,
    COALESCE(SUM(nota), 0)::bigint AS soma_notas,
    COUNT(nota)::bigint AS total_avaliados,
    COUNT(*) FILTER (WHERE EXTRACT(YEAR FROM finalizado_em) = $1::int)::bigint AS jogos_no_ano_atual,
    MIN(finalizado_em)::timestamp AS primeiro_zeramento_em
FROM jogos_zerados
WHERE usuario_id = $2
  AND deleted_at IS NULL
`

type ObterResumoDashboardParams struct {
	AnoAtual  int32
	UsuarioID int32
}

type ObterResumoDashboardRow struct {
	TotalJogos          int64
	TotalSegundos       int64
	SomaNotas           int64
	TotalAvaliados      int64
	JogosNoAnoAtual     int64
	PrimeiroZeramentoEm pgtype.Timestamp
}

func (q *Queries) ObterResumoDashboard(ctx context.Context, arg ObterResumoDashboardParams) (ObterResumoDashboardRow, error) {
	row := q.db.QueryRow(ctx, obterResumoDashboard, arg.AnoAtual, arg.UsuarioID)
	var i ObterResumoDashboardRow
	err := row.Scan(
		&i.TotalJogos,
		&i.TotalSegundos,
		&i.SomaNotas,
		&i.TotalAvaliados,
		&i.JogosNoAnoAtual,
		&i.PrimeiroZeramentoEm,
	)
	return i, err
}
