// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: igdb_cache.sql

package db

import (
	"context"
)

const buscarSnapshotIGDB = `-- name: BuscarSnapshotIGDB :one
SELECT payload FROM igdb_cache WHERE chave = $1
`

func (q *Queries) BuscarSnapshotIGDB(ctx context.Context, chave string) ([]byte, error) {
	row := q.db.QueryRow(ctx, buscarSnapshotIGDB, chave)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const salvarSnapshotIGDB = `-- name: SalvarSnapshotIGDB :exec
INSERT INTO igdb_cache (chave, payload, atualizado_em)
VALUES ($1, $2, now())
ON CONFLICT (chave) DO UPDATE SET payload = EXCLUDED.payload, atualizado_em = now()
`

type SalvarSnapshotIGDBParams struct {
	Chave   string
	Payload []byte
}

func (q *Queries) SalvarSnapshotIGDB(ctx context.Context, arg SalvarSnapshotIGDBParams) error {
	_, err := q.db.Exec(ctx, salvarSnapshotIGDB, arg.Chave, arg.Payload)
	return err
}
