// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jogos_em_andamento.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const criarJogoEmAndamento = `-- name: CriarJogoEmAndamento :one
INSERT INTO jogos_em_andamento (
    usuario_id, igdb_id, igdb_capa_url, nome, iniciado_em
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, usuario_id, igdb_id, igdb_capa_url, nome, iniciado_em, deleted_at, created_at, updated_at
`

type CriarJogoEmAndamentoParams struct {
	UsuarioID   int32
	IgdbID      pgtype.Int4
	IgdbCapaUrl pgtype.Text
	Nome        string
	IniciadoEm  pgtype.Timestamp
}

func (q *Queries) CriarJogoEmAndamento(ctx context.Context, arg CriarJogoEmAndamentoParams) (JogosEmAndamento, error) {
	row := q.db.QueryRow(ctx, criarJogoEmAndamento,
		arg.UsuarioID,
		arg.IgdbID,
		arg.IgdbCapaUrl,
		arg.Nome,
		arg.IniciadoEm,
	)
	var i JogosEmAndamento
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.IgdbCapaUrl,
		&i.Nome,
		&i.IniciadoEm,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const excluirJogoEmAndamento = `-- name: ExcluirJogoEmAndamento :execrows
UPDATE jogos_em_andamento
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type ExcluirJogoEmAndamentoParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) ExcluirJogoEmAndamento(ctx context.Context, arg ExcluirJogoEmAndamentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, excluirJogoEmAndamento, arg.ID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarJogosEmAndamento = `-- name: ListarJogosEmAndamento :many
SELECT id, usuario_id, igdb_id, igdb_capa_url, nome, iniciado_em, deleted_at, created_at, updated_at FROM jogos_em_andamento
WHERE usuario_id = $1 AND deleted_at IS NULL
ORDER BY iniciado_em DESC, id DESC
`

func (q *Queries) ListarJogosEmAndamento(ctx context.Context, usuarioID int32) ([]JogosEmAndamento, error) {
	rows, err := q.db.Query(ctx, listarJogosEmAndamento, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosEmAndamento
	for rows.Next() {
		var i JogosEmAndamento
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.IgdbCapaUrl,
			&i.Nome,
			&i.IniciadoEm,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
