// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jogos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarJogoZerado = `-- name: AtualizarJogoZerado :one
UPDATE jogos_zerados SET
    igdb_id = $3,
    nome = $4,
    console = $5,
    genero = $6,
    tipo = $7,
    iniciado_em = $8,
    finalizado_em = $9,
    tempo_jogado = $10,
    nota = $11,
    dificuldade = $12,
    condicao_zeramento = $13,
    destaque = $14,
    igdb_capa_url = $15,
    igdb_descricao = $16,
    updated_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
RETURNING id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, condicao_zeramento, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at
`

type AtualizarJogoZeradoParams struct {
	ID                int32
	UsuarioID         int32
	IgdbID            pgtype.Int4
	Nome              string
	Console           string
	Genero            pgtype.Text
	Tipo              pgtype.Text
	IniciadoEm        pgtype.Timestamp
	FinalizadoEm      pgtype.Timestamp
	TempoJogado       int32
	Nota              int32
	Dificuldade       Dificuldade
	CondicaoZeramento pgtype.Text
	Destaque          pgtype.Bool
	IgdbCapaUrl       pgtype.Text
	IgdbDescricao     pgtype.Text
}

func (q *Queries) AtualizarJogoZerado(ctx context.Context, arg AtualizarJogoZeradoParams) (JogosZerado, error) {
	row := q.db.QueryRow(ctx, atualizarJogoZerado,
		arg.ID,
		arg.UsuarioID,
		arg.IgdbID,
		arg.Nome,
		arg.Console,
		arg.Genero,
		arg.Tipo,
		arg.IniciadoEm,
		arg.FinalizadoEm,
		arg.TempoJogado,
		arg.Nota,
		arg.Dificuldade,
		arg.CondicaoZeramento,
		arg.Destaque,
		arg.IgdbCapaUrl,
		arg.IgdbDescricao,
	)
	var i JogosZerado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.CondicaoZeramento,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const buscarJogoPorID = `-- name: BuscarJogoPorID :one
SELECT id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, condicao_zeramento, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at FROM jogos_zerados WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type BuscarJogoPorIDParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) BuscarJogoPorID(ctx context.Context, arg BuscarJogoPorIDParams) (JogosZerado, error) {
	row := q.db.QueryRow(ctx, buscarJogoPorID, arg.ID, arg.UsuarioID)
	var i JogosZerado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.CondicaoZeramento,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const criarJogoZerado = `-- name: CriarJogoZerado :one
INSERT INTO jogos_zerados (
    usuario_id, igdb_id, nome, console, genero, tipo,
    iniciado_em, finalizado_em, tempo_jogado, nota,
    dificuldade, condicao_zeramento, destaque, igdb_capa_url, igdb_descricao
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, condicao_zeramento, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at
`

type CriarJogoZeradoParams struct {
	UsuarioID         int32
	IgdbID            pgtype.Int4
	Nome              string
	Console           string
	Genero            pgtype.Text
	Tipo              pgtype.Text
	IniciadoEm        pgtype.Timestamp
	FinalizadoEm      pgtype.Timestamp
	TempoJogado       int32
	Nota              int32
	Dificuldade       Dificuldade
	CondicaoZeramento pgtype.Text
	Destaque          pgtype.Bool
	IgdbCapaUrl       pgtype.Text
	IgdbDescricao     pgtype.Text
}

func (q *Queries) CriarJogoZerado(ctx context.Context, arg CriarJogoZeradoParams) (JogosZerado, error) {
	row := q.db.QueryRow(ctx, criarJogoZerado,
		arg.UsuarioID,
		arg.IgdbID,
		arg.Nome,
		arg.Console,
		arg.Genero,
		arg.Tipo,
		arg.IniciadoEm,
		arg.FinalizadoEm,
		arg.TempoJogado,
		arg.Nota,
		arg.Dificuldade,
		arg.CondicaoZeramento,
		arg.Destaque,
		arg.IgdbCapaUrl,
		arg.IgdbDescricao,
	)
	var i JogosZerado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.CondicaoZeramento,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const excluirJogoZerado = `-- name: ExcluirJogoZerado :execrows
UPDATE jogos_zerados
SET deleted_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type ExcluirJogoZeradoParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) ExcluirJogoZerado(ctx context.Context, arg ExcluirJogoZeradoParams) (int64, error) {
	result, err := q.db.Exec(ctx, excluirJogoZerado, arg.ID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarJogosZerados = `-- name: ListarJogosZerados :many
SELECT id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, condicao_zeramento, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR console = $2)
  AND ($3::varchar IS NULL OR genero = $3)
  AND ($4::int IS NULL OR nota = $4)
  AND ($5::text IS NULL OR nome ILIKE '%' || $5 || '%')
ORDER BY finalizado_em DESC
LIMIT $6 OFFSET $7
`

type ListarJogosZeradosParams struct {
	UsuarioID int32
	Column2   string
	Column3   string
	Column4   int32
	Column5   string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListarJogosZerados(ctx context.Context, arg ListarJogosZeradosParams) ([]JogosZerado, error) {
	rows, err := q.db.Query(ctx, listarJogosZerados,
		arg.UsuarioID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosZerado
	for rows.Next() {
		var i JogosZerado
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.Nome,
			&i.Console,
			&i.Genero,
			&i.Tipo,
			&i.IniciadoEm,
			&i.FinalizadoEm,
			&i.TempoJogado,
			&i.Nota,
			&i.Dificuldade,
			&i.CondicaoZeramento,
			&i.Destaque,
			&i.IgdbCapaUrl,
			&i.IgdbDescricao,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
