// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jogos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarJogoZerado = `-- name: AtualizarJogoZerado :one
UPDATE jogos_zerados SET
    igdb_id = $3,
    nome = $4,
    console = $5,
    genero = $6,
    tipo = $7,
    iniciado_em = $8,
    finalizado_em = $9,
    tempo_jogado = $10,
    nota = $11,
    dificuldade = $12,
    review = $13,
    destaque = $14,
    igdb_capa_url = $15,
    igdb_descricao = $16,
    updated_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
RETURNING id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, review, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at
`

type AtualizarJogoZeradoParams struct {
	ID            int32
	UsuarioID     int32
	IgdbID        pgtype.Int4
	Nome          string
	Console       string
	Genero        pgtype.Text
	Tipo          pgtype.Text
	IniciadoEm    pgtype.Timestamp
	FinalizadoEm  pgtype.Timestamp
	TempoJogado   int32
	Nota          int32
	Dificuldade   Dificuldade
	Review        pgtype.Text
	Destaque      pgtype.Bool
	IgdbCapaUrl   pgtype.Text
	IgdbDescricao pgtype.Text
}

func (q *Queries) AtualizarJogoZerado(ctx context.Context, arg AtualizarJogoZeradoParams) (JogosZerado, error) {
	row := q.db.QueryRow(ctx, atualizarJogoZerado,
		arg.ID,
		arg.UsuarioID,
		arg.IgdbID,
		arg.Nome,
		arg.Console,
		arg.Genero,
		arg.Tipo,
		arg.IniciadoEm,
		arg.FinalizadoEm,
		arg.TempoJogado,
		arg.Nota,
		arg.Dificuldade,
		arg.Review,
		arg.Destaque,
		arg.IgdbCapaUrl,
		arg.IgdbDescricao,
	)
	var i JogosZerado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.Review,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const buscarJogoPorID = `-- name: BuscarJogoPorID :one
SELECT id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, review, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at FROM jogos_zerados WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type BuscarJogoPorIDParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) BuscarJogoPorID(ctx context.Context, arg BuscarJogoPorIDParams) (JogosZerado, error) {
	row := q.db.QueryRow(ctx, buscarJogoPorID, arg.ID, arg.UsuarioID)
	var i JogosZerado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.Review,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contarJogosZerados = `-- name: ContarJogosZerados :one
SELECT COUNT(*) FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
  AND ($4::text IS NULL OR unaccent(genero) ILIKE unaccent('%' || $4::text || '%'))
  AND ($5::varchar IS NULL OR LOWER(tipo) = LOWER($5))
  AND ($6::int IS NULL OR nota >= $6)
  AND ($7::int IS NULL OR nota <= $7)
  AND ($8::int IS NULL OR EXTRACT(YEAR FROM finalizado_em) = $8)
  AND ($9::varchar IS NULL OR dificuldade = $9::dificuldade)
`

type ContarJogosZeradosParams struct {
	UsuarioID   int32
	Busca       pgtype.Text
	Console     pgtype.Text
	Genero      pgtype.Text
	Tipo        pgtype.Text
	NotaMin     pgtype.Int4
	NotaMax     pgtype.Int4
	Ano         pgtype.Int4
	Dificuldade pgtype.Text
}

func (q *Queries) ContarJogosZerados(ctx context.Context, arg ContarJogosZeradosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarJogosZerados,
		arg.UsuarioID,
		arg.Busca,
		arg.Console,
		arg.Genero,
		arg.Tipo,
		arg.NotaMin,
		arg.NotaMax,
		arg.Ano,
		arg.Dificuldade,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarJogoZerado = `-- name: CriarJogoZerado :one
INSERT INTO jogos_zerados (
    usuario_id, igdb_id, nome, console, genero, tipo,
    iniciado_em, finalizado_em, tempo_jogado, nota,
    dificuldade, review, destaque, igdb_capa_url, igdb_descricao
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, review, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at
`

type CriarJogoZeradoParams struct {
	UsuarioID     int32
	IgdbID        pgtype.Int4
	Nome          string
	Console       string
	Genero        pgtype.Text
	Tipo          pgtype.Text
	IniciadoEm    pgtype.Timestamp
	FinalizadoEm  pgtype.Timestamp
	TempoJogado   int32
	Nota          int32
	Dificuldade   Dificuldade
	Review        pgtype.Text
	Destaque      pgtype.Bool
	IgdbCapaUrl   pgtype.Text
	IgdbDescricao pgtype.Text
}

func (q *Queries) CriarJogoZerado(ctx context.Context, arg CriarJogoZeradoParams) (JogosZerado, error) {
	row := q.db.QueryRow(ctx, criarJogoZerado,
		arg.UsuarioID,
		arg.IgdbID,
		arg.Nome,
		arg.Console,
		arg.Genero,
		arg.Tipo,
		arg.IniciadoEm,
		arg.FinalizadoEm,
		arg.TempoJogado,
		arg.Nota,
		arg.Dificuldade,
		arg.Review,
		arg.Destaque,
		arg.IgdbCapaUrl,
		arg.IgdbDescricao,
	)
	var i JogosZerado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.Review,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const excluirJogoZerado = `-- name: ExcluirJogoZerado :execrows
UPDATE jogos_zerados
SET deleted_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type ExcluirJogoZeradoParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) ExcluirJogoZerado(ctx context.Context, arg ExcluirJogoZeradoParams) (int64, error) {
	result, err := q.db.Exec(ctx, excluirJogoZerado, arg.ID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarJogosZerados = `-- name: ListarJogosZerados :many
SELECT id, usuario_id, igdb_id, nome, console, genero, tipo, iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade, review, destaque, igdb_capa_url, igdb_descricao, deleted_at, created_at, updated_at FROM jogos_zerados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
  AND ($4::text IS NULL OR unaccent(genero) ILIKE unaccent('%' || $4::text || '%'))
  AND ($5::varchar IS NULL OR LOWER(tipo) = LOWER($5))
  AND ($6::int IS NULL OR nota >= $6)
  AND ($7::int IS NULL OR nota <= $7)
  AND ($8::int IS NULL OR EXTRACT(YEAR FROM finalizado_em) = $8)
  AND ($9::varchar IS NULL OR dificuldade = $9::dificuldade)
ORDER BY finalizado_em DESC, id DESC
LIMIT $11::int OFFSET $10::int
`

type ListarJogosZeradosParams struct {
	UsuarioID   int32
	Busca       pgtype.Text
	Console     pgtype.Text
	Genero      pgtype.Text
	Tipo        pgtype.Text
	NotaMin     pgtype.Int4
	NotaMax     pgtype.Int4
	Ano         pgtype.Int4
	Dificuldade pgtype.Text
	OffsetVal   int32
	Limite      int32
}

func (q *Queries) ListarJogosZerados(ctx context.Context, arg ListarJogosZeradosParams) ([]JogosZerado, error) {
	rows, err := q.db.Query(ctx, listarJogosZerados,
		arg.UsuarioID,
		arg.Busca,
		arg.Console,
		arg.Genero,
		arg.Tipo,
		arg.NotaMin,
		arg.NotaMax,
		arg.Ano,
		arg.Dificuldade,
		arg.OffsetVal,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosZerado
	for rows.Next() {
		var i JogosZerado
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.Nome,
			&i.Console,
			&i.Genero,
			&i.Tipo,
			&i.IniciadoEm,
			&i.FinalizadoEm,
			&i.TempoJogado,
			&i.Nota,
			&i.Dificuldade,
			&i.Review,
			&i.Destaque,
			&i.IgdbCapaUrl,
			&i.IgdbDescricao,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterAnosUsuario = `-- name: ObterAnosUsuario :many
SELECT DISTINCT EXTRACT(YEAR FROM finalizado_em)::int AS ano
FROM jogos_zerados
WHERE usuario_id = $1 AND deleted_at IS NULL
ORDER BY ano DESC
`

func (q *Queries) ObterAnosUsuario(ctx context.Context, usuarioID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, obterAnosUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var ano int32
		if err := rows.Scan(&ano); err != nil {
			return nil, err
		}
		items = append(items, ano)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterConsolesUsuario = `-- name: ObterConsolesUsuario :many
SELECT DISTINCT console
FROM jogos_zerados
WHERE usuario_id = $1 AND deleted_at IS NULL AND console != ''
ORDER BY console ASC
`

func (q *Queries) ObterConsolesUsuario(ctx context.Context, usuarioID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, obterConsolesUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var console string
		if err := rows.Scan(&console); err != nil {
			return nil, err
		}
		items = append(items, console)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterDetalhesJogoZerado = `-- name: ObterDetalhesJogoZerado :one
WITH jogos_numerados AS (
    SELECT id, usuario_id, igdb_id, nome, console, genero, tipo,
           iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade,
           review, destaque, igdb_capa_url, igdb_descricao, created_at, updated_at, deleted_at,
           ROW_NUMBER() OVER (PARTITION BY usuario_id ORDER BY created_at ASC, id ASC)::int AS numero
    FROM jogos_zerados
    WHERE usuario_id = $2
)
SELECT id, usuario_id, igdb_id, nome, console, genero, tipo,
       iniciado_em, finalizado_em, tempo_jogado, nota, dificuldade,
       review, destaque, igdb_capa_url, igdb_descricao, created_at, updated_at, numero
FROM jogos_numerados
WHERE id = $1 AND deleted_at IS NULL
`

type ObterDetalhesJogoZeradoParams struct {
	ID        int32
	UsuarioID int32
}

type ObterDetalhesJogoZeradoRow struct {
	ID            int32
	UsuarioID     int32
	IgdbID        pgtype.Int4
	Nome          string
	Console       string
	Genero        pgtype.Text
	Tipo          pgtype.Text
	IniciadoEm    pgtype.Timestamp
	FinalizadoEm  pgtype.Timestamp
	TempoJogado   int32
	Nota          int32
	Dificuldade   Dificuldade
	Review        pgtype.Text
	Destaque      pgtype.Bool
	IgdbCapaUrl   pgtype.Text
	IgdbDescricao pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Numero        int32
}

func (q *Queries) ObterDetalhesJogoZerado(ctx context.Context, arg ObterDetalhesJogoZeradoParams) (ObterDetalhesJogoZeradoRow, error) {
	row := q.db.QueryRow(ctx, obterDetalhesJogoZerado, arg.ID, arg.UsuarioID)
	var i ObterDetalhesJogoZeradoRow
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.Tipo,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.TempoJogado,
		&i.Nota,
		&i.Dificuldade,
		&i.Review,
		&i.Destaque,
		&i.IgdbCapaUrl,
		&i.IgdbDescricao,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Numero,
	)
	return i, err
}

const obterGenerosUsuario = `-- name: ObterGenerosUsuario :many
SELECT DISTINCT genero
FROM jogos_zerados
WHERE usuario_id = $1 AND deleted_at IS NULL AND genero IS NOT NULL AND genero != ''
`

func (q *Queries) ObterGenerosUsuario(ctx context.Context, usuarioID int32) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, obterGenerosUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var genero pgtype.Text
		if err := rows.Scan(&genero); err != nil {
			return nil, err
		}
		items = append(items, genero)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterTiposUsuario = `-- name: ObterTiposUsuario :many
SELECT DISTINCT tipo
FROM jogos_zerados
WHERE usuario_id = $1 AND deleted_at IS NULL AND tipo IS NOT NULL AND tipo != ''
ORDER BY tipo ASC
`

func (q *Queries) ObterTiposUsuario(ctx context.Context, usuarioID int32) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, obterTiposUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var tipo pgtype.Text
		if err := rows.Scan(&tipo); err != nil {
			return nil, err
		}
		items = append(items, tipo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
