// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jogos_abandonados.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarJogoAbandonado = `-- name: AtualizarJogoAbandonado :one
UPDATE jogos_abandonados SET
    igdb_id = $3,
    igdb_capa_url = $4,
    nome = $5,
    console = $6,
    tempo_jogado = $7,
    motivo = $8,
    abandonado_em = $9,
    iniciado_em = $10,
    updated_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
RETURNING id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em
`

type AtualizarJogoAbandonadoParams struct {
	ID           int32
	UsuarioID    int32
	IgdbID       pgtype.Int4
	IgdbCapaUrl  pgtype.Text
	Nome         string
	Console      string
	TempoJogado  int32
	Motivo       pgtype.Text
	AbandonadoEm pgtype.Timestamp
	IniciadoEm   pgtype.Timestamp
}

func (q *Queries) AtualizarJogoAbandonado(ctx context.Context, arg AtualizarJogoAbandonadoParams) (JogosAbandonado, error) {
	row := q.db.QueryRow(ctx, atualizarJogoAbandonado,
		arg.ID,
		arg.UsuarioID,
		arg.IgdbID,
		arg.IgdbCapaUrl,
		arg.Nome,
		arg.Console,
		arg.TempoJogado,
		arg.Motivo,
		arg.AbandonadoEm,
		arg.IniciadoEm,
	)
	var i JogosAbandonado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.IgdbCapaUrl,
		&i.Nome,
		&i.Console,
		&i.TempoJogado,
		&i.Motivo,
		&i.AbandonadoEm,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IniciadoEm,
	)
	return i, err
}

const buscarJogoAbandonadoPorID = `-- name: BuscarJogoAbandonadoPorID :one
SELECT id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em FROM jogos_abandonados
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type BuscarJogoAbandonadoPorIDParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) BuscarJogoAbandonadoPorID(ctx context.Context, arg BuscarJogoAbandonadoPorIDParams) (JogosAbandonado, error) {
	row := q.db.QueryRow(ctx, buscarJogoAbandonadoPorID, arg.ID, arg.UsuarioID)
	var i JogosAbandonado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.IgdbCapaUrl,
		&i.Nome,
		&i.Console,
		&i.TempoJogado,
		&i.Motivo,
		&i.AbandonadoEm,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IniciadoEm,
	)
	return i, err
}

const contarJogosAbandonados = `-- name: ContarJogosAbandonados :one
SELECT COUNT(*) FROM jogos_abandonados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
`

type ContarJogosAbandonadosParams struct {
	UsuarioID int32
	Busca     pgtype.Text
	Console   pgtype.Text
}

func (q *Queries) ContarJogosAbandonados(ctx context.Context, arg ContarJogosAbandonadosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarJogosAbandonados, arg.UsuarioID, arg.Busca, arg.Console)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarJogoAbandonado = `-- name: CriarJogoAbandonado :one
INSERT INTO jogos_abandonados (
    usuario_id, igdb_id, igdb_capa_url, nome, console,
    tempo_jogado, motivo, abandonado_em, iniciado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em
`

type CriarJogoAbandonadoParams struct {
	UsuarioID    int32
	IgdbID       pgtype.Int4
	IgdbCapaUrl  pgtype.Text
	Nome         string
	Console      string
	TempoJogado  int32
	Motivo       pgtype.Text
	AbandonadoEm pgtype.Timestamp
	IniciadoEm   pgtype.Timestamp
}

func (q *Queries) CriarJogoAbandonado(ctx context.Context, arg CriarJogoAbandonadoParams) (JogosAbandonado, error) {
	row := q.db.QueryRow(ctx, criarJogoAbandonado,
		arg.UsuarioID,
		arg.IgdbID,
		arg.IgdbCapaUrl,
		arg.Nome,
		arg.Console,
		arg.TempoJogado,
		arg.Motivo,
		arg.AbandonadoEm,
		arg.IniciadoEm,
	)
	var i JogosAbandonado
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.IgdbCapaUrl,
		&i.Nome,
		&i.Console,
		&i.TempoJogado,
		&i.Motivo,
		&i.AbandonadoEm,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IniciadoEm,
	)
	return i, err
}

const excluirJogoAbandonado = `-- name: ExcluirJogoAbandonado :execrows
UPDATE jogos_abandonados
SET deleted_at = now()
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type ExcluirJogoAbandonadoParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) ExcluirJogoAbandonado(ctx context.Context, arg ExcluirJogoAbandonadoParams) (int64, error) {
	result, err := q.db.Exec(ctx, excluirJogoAbandonado, arg.ID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarJogosAbandonadosAntigos = `-- name: ListarJogosAbandonadosAntigos :many
SELECT id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em FROM jogos_abandonados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
ORDER BY abandonado_em ASC, id ASC
LIMIT $5::int OFFSET $4::int
`

type ListarJogosAbandonadosAntigosParams struct {
	UsuarioID int32
	Busca     pgtype.Text
	Console   pgtype.Text
	OffsetVal int32
	Limite    int32
}

func (q *Queries) ListarJogosAbandonadosAntigos(ctx context.Context, arg ListarJogosAbandonadosAntigosParams) ([]JogosAbandonado, error) {
	rows, err := q.db.Query(ctx, listarJogosAbandonadosAntigos,
		arg.UsuarioID,
		arg.Busca,
		arg.Console,
		arg.OffsetVal,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosAbandonado
	for rows.Next() {
		var i JogosAbandonado
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.IgdbCapaUrl,
			&i.Nome,
			&i.Console,
			&i.TempoJogado,
			&i.Motivo,
			&i.AbandonadoEm,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IniciadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarJogosAbandonadosNome = `-- name: ListarJogosAbandonadosNome :many
SELECT id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em FROM jogos_abandonados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
ORDER BY unaccent(nome) ASC, id ASC
LIMIT $5::int OFFSET $4::int
`

type ListarJogosAbandonadosNomeParams struct {
	UsuarioID int32
	Busca     pgtype.Text
	Console   pgtype.Text
	OffsetVal int32
	Limite    int32
}

func (q *Queries) ListarJogosAbandonadosNome(ctx context.Context, arg ListarJogosAbandonadosNomeParams) ([]JogosAbandonado, error) {
	rows, err := q.db.Query(ctx, listarJogosAbandonadosNome,
		arg.UsuarioID,
		arg.Busca,
		arg.Console,
		arg.OffsetVal,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosAbandonado
	for rows.Next() {
		var i JogosAbandonado
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.IgdbCapaUrl,
			&i.Nome,
			&i.Console,
			&i.TempoJogado,
			&i.Motivo,
			&i.AbandonadoEm,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IniciadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarJogosAbandonadosRecentes = `-- name: ListarJogosAbandonadosRecentes :many
SELECT id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em FROM jogos_abandonados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
ORDER BY abandonado_em DESC, id DESC
LIMIT $5::int OFFSET $4::int
`

type ListarJogosAbandonadosRecentesParams struct {
	UsuarioID int32
	Busca     pgtype.Text
	Console   pgtype.Text
	OffsetVal int32
	Limite    int32
}

func (q *Queries) ListarJogosAbandonadosRecentes(ctx context.Context, arg ListarJogosAbandonadosRecentesParams) ([]JogosAbandonado, error) {
	rows, err := q.db.Query(ctx, listarJogosAbandonadosRecentes,
		arg.UsuarioID,
		arg.Busca,
		arg.Console,
		arg.OffsetVal,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosAbandonado
	for rows.Next() {
		var i JogosAbandonado
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.IgdbCapaUrl,
			&i.Nome,
			&i.Console,
			&i.TempoJogado,
			&i.Motivo,
			&i.AbandonadoEm,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IniciadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarJogosAbandonadosTempo = `-- name: ListarJogosAbandonadosTempo :many
SELECT id, usuario_id, igdb_id, igdb_capa_url, nome, console, tempo_jogado, motivo, abandonado_em, deleted_at, created_at, updated_at, iniciado_em FROM jogos_abandonados
WHERE usuario_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR unaccent(nome) ILIKE unaccent('%' || $2::text || '%'))
  AND ($3::varchar IS NULL OR console = $3)
ORDER BY tempo_jogado DESC, id DESC
LIMIT $5::int OFFSET $4::int
`

type ListarJogosAbandonadosTempoParams struct {
	UsuarioID int32
	Busca     pgtype.Text
	Console   pgtype.Text
	OffsetVal int32
	Limite    int32
}

func (q *Queries) ListarJogosAbandonadosTempo(ctx context.Context, arg ListarJogosAbandonadosTempoParams) ([]JogosAbandonado, error) {
	rows, err := q.db.Query(ctx, listarJogosAbandonadosTempo,
		arg.UsuarioID,
		arg.Busca,
		arg.Console,
		arg.OffsetVal,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JogosAbandonado
	for rows.Next() {
		var i JogosAbandonado
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.IgdbCapaUrl,
			&i.Nome,
			&i.Console,
			&i.TempoJogado,
			&i.Motivo,
			&i.AbandonadoEm,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IniciadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterConsolesAbandonadosUsuario = `-- name: ObterConsolesAbandonadosUsuario :many
SELECT DISTINCT console
FROM jogos_abandonados
WHERE usuario_id = $1 AND deleted_at IS NULL AND console != ''
ORDER BY console ASC
`

func (q *Queries) ObterConsolesAbandonadosUsuario(ctx context.Context, usuarioID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, obterConsolesAbandonadosUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var console string
		if err := rows.Scan(&console); err != nil {
			return nil, err
		}
		items = append(items, console)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterTotalAbandonadosUsuario = `-- name: ObterTotalAbandonadosUsuario :one
SELECT COUNT(*) FROM jogos_abandonados
WHERE usuario_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ObterTotalAbandonadosUsuario(ctx context.Context, usuarioID int32) (int64, error) {
	row := q.db.QueryRow(ctx, obterTotalAbandonadosUsuario, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
