// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const associarJogoZeradoItem = `-- name: AssociarJogoZeradoItem :one
UPDATE lista_itens
SET jogo_zerado_id = $3
WHERE id = $1 AND lista_id = $2
RETURNING id, lista_id, igdb_id, nome, console, igdb_capa_url, ano_lancamento, posicao, jogo_zerado_id, created_at
`

type AssociarJogoZeradoItemParams struct {
	ID           int64
	ListaID      int64
	JogoZeradoID pgtype.Int4
}

func (q *Queries) AssociarJogoZeradoItem(ctx context.Context, arg AssociarJogoZeradoItemParams) (ListaIten, error) {
	row := q.db.QueryRow(ctx, associarJogoZeradoItem, arg.ID, arg.ListaID, arg.JogoZeradoID)
	var i ListaIten
	err := row.Scan(
		&i.ID,
		&i.ListaID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.IgdbCapaUrl,
		&i.AnoLancamento,
		&i.Posicao,
		&i.JogoZeradoID,
		&i.CreatedAt,
	)
	return i, err
}

const atualizarLista = `-- name: AtualizarLista :one
UPDATE listas
SET nome = $3,
    descricao = $4,
    updated_at = now()
WHERE id = $1 AND usuario_id = $2
RETURNING id, usuario_id, tipo, nome, descricao, regra_tipo, regra_valor, regra_igdb_id, meta, created_at, updated_at, posicao
`

type AtualizarListaParams struct {
	ID        int64
	UsuarioID int32
	Nome      string
	Descricao pgtype.Text
}

func (q *Queries) AtualizarLista(ctx context.Context, arg AtualizarListaParams) (Lista, error) {
	row := q.db.QueryRow(ctx, atualizarLista,
		arg.ID,
		arg.UsuarioID,
		arg.Nome,
		arg.Descricao,
	)
	var i Lista
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Nome,
		&i.Descricao,
		&i.RegraTipo,
		&i.RegraValor,
		&i.RegraIgdbID,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posicao,
	)
	return i, err
}

const atualizarPosicaoItem = `-- name: AtualizarPosicaoItem :exec
UPDATE lista_itens
SET posicao = $3
WHERE id = $1 AND lista_id = $2
`

type AtualizarPosicaoItemParams struct {
	ID      int64
	ListaID int64
	Posicao int32
}

func (q *Queries) AtualizarPosicaoItem(ctx context.Context, arg AtualizarPosicaoItemParams) error {
	_, err := q.db.Exec(ctx, atualizarPosicaoItem, arg.ID, arg.ListaID, arg.Posicao)
	return err
}

const buscarItemPorID = `-- name: BuscarItemPorID :one
SELECT i.id, i.lista_id, i.igdb_id, i.nome, i.console, i.igdb_capa_url, i.ano_lancamento, i.posicao, i.jogo_zerado_id, i.created_at
FROM lista_itens i
JOIN listas l ON l.id = i.lista_id
WHERE i.id = $1 AND l.usuario_id = $2
`

type BuscarItemPorIDParams struct {
	ID        int64
	UsuarioID int32
}

func (q *Queries) BuscarItemPorID(ctx context.Context, arg BuscarItemPorIDParams) (ListaIten, error) {
	row := q.db.QueryRow(ctx, buscarItemPorID, arg.ID, arg.UsuarioID)
	var i ListaIten
	err := row.Scan(
		&i.ID,
		&i.ListaID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.IgdbCapaUrl,
		&i.AnoLancamento,
		&i.Posicao,
		&i.JogoZeradoID,
		&i.CreatedAt,
	)
	return i, err
}

const buscarJogoZeradoDoUsuario = `-- name: BuscarJogoZeradoDoUsuario :one
SELECT id, usuario_id, igdb_id, nome, console, genero, finalizado_em, nota, igdb_capa_url
FROM jogos_zerados
WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
`

type BuscarJogoZeradoDoUsuarioParams struct {
	ID        int32
	UsuarioID int32
}

type BuscarJogoZeradoDoUsuarioRow struct {
	ID           int32
	UsuarioID    int32
	IgdbID       pgtype.Int4
	Nome         string
	Console      string
	Genero       pgtype.Text
	FinalizadoEm pgtype.Timestamp
	Nota         int32
	IgdbCapaUrl  pgtype.Text
}

func (q *Queries) BuscarJogoZeradoDoUsuario(ctx context.Context, arg BuscarJogoZeradoDoUsuarioParams) (BuscarJogoZeradoDoUsuarioRow, error) {
	row := q.db.QueryRow(ctx, buscarJogoZeradoDoUsuario, arg.ID, arg.UsuarioID)
	var i BuscarJogoZeradoDoUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.Genero,
		&i.FinalizadoEm,
		&i.Nota,
		&i.IgdbCapaUrl,
	)
	return i, err
}

const buscarListaPorID = `-- name: BuscarListaPorID :one
SELECT id, usuario_id, tipo, nome, descricao, regra_tipo, regra_valor, regra_igdb_id, meta, created_at, updated_at, posicao FROM listas
WHERE id = $1 AND usuario_id = $2
`

type BuscarListaPorIDParams struct {
	ID        int64
	UsuarioID int32
}

func (q *Queries) BuscarListaPorID(ctx context.Context, arg BuscarListaPorIDParams) (Lista, error) {
	row := q.db.QueryRow(ctx, buscarListaPorID, arg.ID, arg.UsuarioID)
	var i Lista
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Nome,
		&i.Descricao,
		&i.RegraTipo,
		&i.RegraValor,
		&i.RegraIgdbID,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posicao,
	)
	return i, err
}

const buscarListaPorIDParaUpdate = `-- name: BuscarListaPorIDParaUpdate :one
SELECT id, usuario_id, tipo, nome, descricao, regra_tipo, regra_valor, regra_igdb_id, meta, created_at, updated_at, posicao FROM listas
WHERE id = $1 AND usuario_id = $2
FOR UPDATE
`

type BuscarListaPorIDParaUpdateParams struct {
	ID        int64
	UsuarioID int32
}

func (q *Queries) BuscarListaPorIDParaUpdate(ctx context.Context, arg BuscarListaPorIDParaUpdateParams) (Lista, error) {
	row := q.db.QueryRow(ctx, buscarListaPorIDParaUpdate, arg.ID, arg.UsuarioID)
	var i Lista
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Nome,
		&i.Descricao,
		&i.RegraTipo,
		&i.RegraValor,
		&i.RegraIgdbID,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posicao,
	)
	return i, err
}

const criarItemLista = `-- name: CriarItemLista :one
INSERT INTO lista_itens (
    lista_id, igdb_id, nome, console, igdb_capa_url, ano_lancamento, posicao, jogo_zerado_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, lista_id, igdb_id, nome, console, igdb_capa_url, ano_lancamento, posicao, jogo_zerado_id, created_at
`

type CriarItemListaParams struct {
	ListaID       int64
	IgdbID        pgtype.Int4
	Nome          string
	Console       pgtype.Text
	IgdbCapaUrl   pgtype.Text
	AnoLancamento pgtype.Int4
	Posicao       int32
	JogoZeradoID  pgtype.Int4
}

func (q *Queries) CriarItemLista(ctx context.Context, arg CriarItemListaParams) (ListaIten, error) {
	row := q.db.QueryRow(ctx, criarItemLista,
		arg.ListaID,
		arg.IgdbID,
		arg.Nome,
		arg.Console,
		arg.IgdbCapaUrl,
		arg.AnoLancamento,
		arg.Posicao,
		arg.JogoZeradoID,
	)
	var i ListaIten
	err := row.Scan(
		&i.ID,
		&i.ListaID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.IgdbCapaUrl,
		&i.AnoLancamento,
		&i.Posicao,
		&i.JogoZeradoID,
		&i.CreatedAt,
	)
	return i, err
}

const criarLista = `-- name: CriarLista :one
INSERT INTO listas (
    usuario_id, tipo, nome, descricao, regra_tipo, regra_valor, regra_igdb_id, posicao
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    COALESCE((SELECT MAX(posicao) + 1 FROM listas WHERE usuario_id = $1 AND tipo = $2), 1)
) RETURNING id, usuario_id, tipo, nome, descricao, regra_tipo, regra_valor, regra_igdb_id, meta, created_at, updated_at, posicao
`

type CriarListaParams struct {
	UsuarioID   int32
	Tipo        ListaTipo
	Nome        string
	Descricao   pgtype.Text
	RegraTipo   NullListaRegraTipo
	RegraValor  pgtype.Text
	RegraIgdbID pgtype.Int4
}

func (q *Queries) CriarLista(ctx context.Context, arg CriarListaParams) (Lista, error) {
	row := q.db.QueryRow(ctx, criarLista,
		arg.UsuarioID,
		arg.Tipo,
		arg.Nome,
		arg.Descricao,
		arg.RegraTipo,
		arg.RegraValor,
		arg.RegraIgdbID,
	)
	var i Lista
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Nome,
		&i.Descricao,
		&i.RegraTipo,
		&i.RegraValor,
		&i.RegraIgdbID,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posicao,
	)
	return i, err
}

const desassociarJogoZeradoItem = `-- name: DesassociarJogoZeradoItem :one
UPDATE lista_itens
SET jogo_zerado_id = NULL
WHERE id = $1 AND lista_id = $2
RETURNING id, lista_id, igdb_id, nome, console, igdb_capa_url, ano_lancamento, posicao, jogo_zerado_id, created_at
`

type DesassociarJogoZeradoItemParams struct {
	ID      int64
	ListaID int64
}

func (q *Queries) DesassociarJogoZeradoItem(ctx context.Context, arg DesassociarJogoZeradoItemParams) (ListaIten, error) {
	row := q.db.QueryRow(ctx, desassociarJogoZeradoItem, arg.ID, arg.ListaID)
	var i ListaIten
	err := row.Scan(
		&i.ID,
		&i.ListaID,
		&i.IgdbID,
		&i.Nome,
		&i.Console,
		&i.IgdbCapaUrl,
		&i.AnoLancamento,
		&i.Posicao,
		&i.JogoZeradoID,
		&i.CreatedAt,
	)
	return i, err
}

const excluirItem = `-- name: ExcluirItem :execrows
DELETE FROM lista_itens
WHERE id = $1 AND lista_id = $2
`

type ExcluirItemParams struct {
	ID      int64
	ListaID int64
}

func (q *Queries) ExcluirItem(ctx context.Context, arg ExcluirItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, excluirItem, arg.ID, arg.ListaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const excluirLista = `-- name: ExcluirLista :execrows
DELETE FROM listas
WHERE id = $1 AND usuario_id = $2
`

type ExcluirListaParams struct {
	ID        int64
	UsuarioID int32
}

func (q *Queries) ExcluirLista(ctx context.Context, arg ExcluirListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, excluirLista, arg.ID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarItensPorLista = `-- name: ListarItensPorLista :many
SELECT i.id, i.lista_id, i.igdb_id, i.nome, i.console, i.igdb_capa_url, i.ano_lancamento, i.posicao, i.jogo_zerado_id, i.created_at
FROM lista_itens i
WHERE i.lista_id = $1
ORDER BY i.posicao ASC, i.id ASC
`

func (q *Queries) ListarItensPorLista(ctx context.Context, listaID int64) ([]ListaIten, error) {
	rows, err := q.db.Query(ctx, listarItensPorLista, listaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListaIten
	for rows.Next() {
		var i ListaIten
		if err := rows.Scan(
			&i.ID,
			&i.ListaID,
			&i.IgdbID,
			&i.Nome,
			&i.Console,
			&i.IgdbCapaUrl,
			&i.AnoLancamento,
			&i.Posicao,
			&i.JogoZeradoID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarJogosZeradosUsuarioParaMatching = `-- name: ListarJogosZeradosUsuarioParaMatching :many
SELECT id, usuario_id, igdb_id, nome, console, genero, finalizado_em, nota, igdb_capa_url
FROM jogos_zerados
WHERE usuario_id = $1 AND deleted_at IS NULL
ORDER BY finalizado_em ASC, id ASC
`

type ListarJogosZeradosUsuarioParaMatchingRow struct {
	ID           int32
	UsuarioID    int32
	IgdbID       pgtype.Int4
	Nome         string
	Console      string
	Genero       pgtype.Text
	FinalizadoEm pgtype.Timestamp
	Nota         int32
	IgdbCapaUrl  pgtype.Text
}

func (q *Queries) ListarJogosZeradosUsuarioParaMatching(ctx context.Context, usuarioID int32) ([]ListarJogosZeradosUsuarioParaMatchingRow, error) {
	rows, err := q.db.Query(ctx, listarJogosZeradosUsuarioParaMatching, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarJogosZeradosUsuarioParaMatchingRow
	for rows.Next() {
		var i ListarJogosZeradosUsuarioParaMatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.IgdbID,
			&i.Nome,
			&i.Console,
			&i.Genero,
			&i.FinalizadoEm,
			&i.Nota,
			&i.IgdbCapaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarListasPorUsuario = `-- name: ListarListasPorUsuario :many
SELECT id, usuario_id, tipo, nome, descricao, regra_tipo, regra_valor, regra_igdb_id, meta, created_at, updated_at, posicao FROM listas
WHERE usuario_id = $1
ORDER BY tipo, posicao ASC, id ASC
`

func (q *Queries) ListarListasPorUsuario(ctx context.Context, usuarioID int32) ([]Lista, error) {
	rows, err := q.db.Query(ctx, listarListasPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lista
	for rows.Next() {
		var i Lista
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Tipo,
			&i.Nome,
			&i.Descricao,
			&i.RegraTipo,
			&i.RegraValor,
			&i.RegraIgdbID,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Posicao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTodosItensDoUsuario = `-- name: ListarTodosItensDoUsuario :many
SELECT i.id, i.lista_id, i.igdb_id, i.nome, i.console, i.igdb_capa_url, i.ano_lancamento, i.posicao, i.jogo_zerado_id, i.created_at
FROM lista_itens i
JOIN listas l ON l.id = i.lista_id
WHERE l.usuario_id = $1
ORDER BY i.lista_id, i.posicao ASC, i.id ASC
`

func (q *Queries) ListarTodosItensDoUsuario(ctx context.Context, usuarioID int32) ([]ListaIten, error) {
	rows, err := q.db.Query(ctx, listarTodosItensDoUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListaIten
	for rows.Next() {
		var i ListaIten
		if err := rows.Scan(
			&i.ID,
			&i.ListaID,
			&i.IgdbID,
			&i.Nome,
			&i.Console,
			&i.IgdbCapaUrl,
			&i.AnoLancamento,
			&i.Posicao,
			&i.JogoZeradoID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterMaxPosicaoItem = `-- name: ObterMaxPosicaoItem :one
SELECT COALESCE(MAX(posicao), 0)::int AS max_posicao
FROM lista_itens
WHERE lista_id = $1
`

func (q *Queries) ObterMaxPosicaoItem(ctx context.Context, listaID int64) (int32, error) {
	row := q.db.QueryRow(ctx, obterMaxPosicaoItem, listaID)
	var max_posicao int32
	err := row.Scan(&max_posicao)
	return max_posicao, err
}
