// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Dificuldade string

const (
	DificuldadeC   Dificuldade = "C"
	DificuldadeB   Dificuldade = "B"
	DificuldadeA   Dificuldade = "A"
	DificuldadeAA  Dificuldade = "AA"
	DificuldadeAAA Dificuldade = "AAA"
)

func (e *Dificuldade) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Dificuldade(s)
	case string:
		*e = Dificuldade(s)
	default:
		return fmt.Errorf("unsupported scan type for Dificuldade: %T", src)
	}
	return nil
}

type NullDificuldade struct {
	Dificuldade Dificuldade
	Valid       bool // Valid is true if Dificuldade is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDificuldade) Scan(value interface{}) error {
	if value == nil {
		ns.Dificuldade, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Dificuldade.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDificuldade) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Dificuldade), nil
}

type ListaRegraTipo string

const (
	ListaRegraTipoFranquia   ListaRegraTipo = "franquia"
	ListaRegraTipoPlataforma ListaRegraTipo = "plataforma"
	ListaRegraTipoGenero     ListaRegraTipo = "genero"
	ListaRegraTipoManual     ListaRegraTipo = "manual"
)

func (e *ListaRegraTipo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListaRegraTipo(s)
	case string:
		*e = ListaRegraTipo(s)
	default:
		return fmt.Errorf("unsupported scan type for ListaRegraTipo: %T", src)
	}
	return nil
}

type NullListaRegraTipo struct {
	ListaRegraTipo ListaRegraTipo
	Valid          bool // Valid is true if ListaRegraTipo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListaRegraTipo) Scan(value interface{}) error {
	if value == nil {
		ns.ListaRegraTipo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListaRegraTipo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListaRegraTipo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListaRegraTipo), nil
}

type ListaTipo string

const (
	ListaTipoFila    ListaTipo = "fila"
	ListaTipoDesafio ListaTipo = "desafio"
)

func (e *ListaTipo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListaTipo(s)
	case string:
		*e = ListaTipo(s)
	default:
		return fmt.Errorf("unsupported scan type for ListaTipo: %T", src)
	}
	return nil
}

type NullListaTipo struct {
	ListaTipo ListaTipo
	Valid     bool // Valid is true if ListaTipo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListaTipo) Scan(value interface{}) error {
	if value == nil {
		ns.ListaTipo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListaTipo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListaTipo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListaTipo), nil
}

type TipoDesafio string

const (
	TipoDesafioQUANTIDADE    TipoDesafio = "QUANTIDADE"
	TipoDesafioLISTACOMPLETA TipoDesafio = "LISTA_COMPLETA"
	TipoDesafioFRANQUIA      TipoDesafio = "FRANQUIA"
	TipoDesafioEMPRESA       TipoDesafio = "EMPRESA"
	TipoDesafioGENERO        TipoDesafio = "GENERO"
	TipoDesafioMANUAL        TipoDesafio = "MANUAL"
)

func (e *TipoDesafio) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoDesafio(s)
	case string:
		*e = TipoDesafio(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoDesafio: %T", src)
	}
	return nil
}

type NullTipoDesafio struct {
	TipoDesafio TipoDesafio
	Valid       bool // Valid is true if TipoDesafio is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoDesafio) Scan(value interface{}) error {
	if value == nil {
		ns.TipoDesafio, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoDesafio.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoDesafio) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoDesafio), nil
}

type TipoFavorito string

const (
	TipoFavoritoJOGO   TipoFavorito = "JOGO"
	TipoFavoritoGENERO TipoFavorito = "GENERO"
	TipoFavoritoTIPO   TipoFavorito = "TIPO"
)

func (e *TipoFavorito) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoFavorito(s)
	case string:
		*e = TipoFavorito(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoFavorito: %T", src)
	}
	return nil
}

type NullTipoFavorito struct {
	TipoFavorito TipoFavorito
	Valid        bool // Valid is true if TipoFavorito is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoFavorito) Scan(value interface{}) error {
	if value == nil {
		ns.TipoFavorito, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoFavorito.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoFavorito) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoFavorito), nil
}

type Campanha struct {
	ID        int32
	UsuarioID int32
	Nome      string
	Descricao pgtype.Text
	Icone     pgtype.Text
	Concluida pgtype.Bool
	CreatedAt pgtype.Timestamp
}

type Conquista struct {
	ID            int32
	UsuarioID     int32
	DesafioID     pgtype.Int4
	CampanhaID    pgtype.Int4
	Nome          string
	Descricao     pgtype.Text
	Badge         pgtype.Text
	DataConquista pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}

type Desafio struct {
	ID            int32
	UsuarioID     int32
	CampanhaID    pgtype.Int4
	Nome          string
	Tipo          TipoDesafio
	FiltroValor   pgtype.Text
	Meta          pgtype.Int4
	Concluido     pgtype.Bool
	DataConclusao pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}

type DesafioIten struct {
	ID          int32
	DesafioID   int32
	IgdbID      pgtype.Int4
	Nome        string
	Concluido   pgtype.Bool
	ZeramentoID pgtype.Int4
	NaColecao   pgtype.Bool
}

type Favorito struct {
	ID        int32
	UsuarioID int32
	JogoID    pgtype.Int4
	Tipo      TipoFavorito
	Posicao   int32
	CreatedAt pgtype.Timestamp
}

type IgdbCache struct {
	Chave        string
	Payload      []byte
	AtualizadoEm pgtype.Timestamptz
}

type JogosZerado struct {
	ID            int32
	UsuarioID     int32
	IgdbID        pgtype.Int4
	Nome          string
	Console       string
	Genero        pgtype.Text
	Tipo          pgtype.Text
	IniciadoEm    pgtype.Timestamp
	FinalizadoEm  pgtype.Timestamp
	TempoJogado   int32
	Nota          int32
	Dificuldade   Dificuldade
	Review        pgtype.Text
	Destaque      pgtype.Bool
	IgdbCapaUrl   pgtype.Text
	IgdbDescricao pgtype.Text
	DeletedAt     pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type LimitesSolicitacaoResetSenha struct {
	Email            string
	JanelaIniciadaEm pgtype.Timestamptz
	Quantidade       int16
}

type Lista struct {
	ID          int64
	UsuarioID   int32
	Tipo        ListaTipo
	Nome        string
	Descricao   pgtype.Text
	RegraTipo   NullListaRegraTipo
	RegraValor  pgtype.Text
	RegraIgdbID pgtype.Int4
	Meta        pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ListaIten struct {
	ID            int64
	ListaID       int64
	IgdbID        pgtype.Int4
	Nome          string
	Console       pgtype.Text
	IgdbCapaUrl   pgtype.Text
	AnoLancamento pgtype.Int4
	Posicao       int32
	JogoZeradoID  pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

type TokensRefreshAtivo struct {
	Jti       string
	UsuarioID int32
	ExpiraEm  pgtype.Timestamptz
}

type TokensResetSenha struct {
	ID        int32
	UsuarioID int32
	TokenHash string
	ExpiraEm  pgtype.Timestamptz
	UsadoEm   pgtype.Timestamptz
}

type TokensRevogado struct {
	Jti      string
	ExpiraEm pgtype.Timestamptz
}

type Usuario struct {
	ID           int32
	Nome         string
	Email        string
	SenhaHash    string
	Username     pgtype.Text
	AvatarUrl    pgtype.Text
	Bio          pgtype.Text
	RedesSociais []byte
	CreatedAt    pgtype.Timestamp
	Idioma       string
}
