// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferencias.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarIdiomaUsuario = `-- name: AtualizarIdiomaUsuario :execrows
UPDATE usuarios
SET idioma = $2
WHERE id = $1
`

type AtualizarIdiomaUsuarioParams struct {
	ID     int32
	Idioma string
}

func (q *Queries) AtualizarIdiomaUsuario(ctx context.Context, arg AtualizarIdiomaUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, atualizarIdiomaUsuario, arg.ID, arg.Idioma)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarPreferenciasPorUsuarioID = `-- name: BuscarPreferenciasPorUsuarioID :one
SELECT
    u.idioma,
    p.formato_data,
    p.fuso_horario,
    p.visual_biblioteca,
    p.itens_por_pagina,
    p.reduzir_animacoes,
    p.modo_tema,
    p.estilo_tema,
    p.updated_at
FROM usuarios u
LEFT JOIN preferencias_usuario p ON p.usuario_id = u.id
WHERE u.id = $1
`

type BuscarPreferenciasPorUsuarioIDRow struct {
	Idioma           string
	FormatoData      pgtype.Text
	FusoHorario      pgtype.Text
	VisualBiblioteca pgtype.Text
	ItensPorPagina   pgtype.Int4
	ReduzirAnimacoes pgtype.Bool
	ModoTema         pgtype.Text
	EstiloTema       pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) BuscarPreferenciasPorUsuarioID(ctx context.Context, id int32) (BuscarPreferenciasPorUsuarioIDRow, error) {
	row := q.db.QueryRow(ctx, buscarPreferenciasPorUsuarioID, id)
	var i BuscarPreferenciasPorUsuarioIDRow
	err := row.Scan(
		&i.Idioma,
		&i.FormatoData,
		&i.FusoHorario,
		&i.VisualBiblioteca,
		&i.ItensPorPagina,
		&i.ReduzirAnimacoes,
		&i.ModoTema,
		&i.EstiloTema,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPreferenciasUsuario = `-- name: UpsertPreferenciasUsuario :one
INSERT INTO preferencias_usuario (
    usuario_id,
    formato_data,
    fuso_horario,
    visual_biblioteca,
    itens_por_pagina,
    reduzir_animacoes,
    modo_tema,
    estilo_tema,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now()
)
ON CONFLICT (usuario_id) DO UPDATE SET
    formato_data = EXCLUDED.formato_data,
    fuso_horario = EXCLUDED.fuso_horario,
    visual_biblioteca = EXCLUDED.visual_biblioteca,
    itens_por_pagina = EXCLUDED.itens_por_pagina,
    reduzir_animacoes = EXCLUDED.reduzir_animacoes,
    modo_tema = EXCLUDED.modo_tema,
    estilo_tema = EXCLUDED.estilo_tema,
    updated_at = now()
RETURNING usuario_id, formato_data, fuso_horario, visual_biblioteca, itens_por_pagina, reduzir_animacoes, modo_tema, estilo_tema, updated_at
`

type UpsertPreferenciasUsuarioParams struct {
	UsuarioID        int32
	FormatoData      string
	FusoHorario      string
	VisualBiblioteca string
	ItensPorPagina   int32
	ReduzirAnimacoes bool
	ModoTema         string
	EstiloTema       string
}

func (q *Queries) UpsertPreferenciasUsuario(ctx context.Context, arg UpsertPreferenciasUsuarioParams) (PreferenciasUsuario, error) {
	row := q.db.QueryRow(ctx, upsertPreferenciasUsuario,
		arg.UsuarioID,
		arg.FormatoData,
		arg.FusoHorario,
		arg.VisualBiblioteca,
		arg.ItensPorPagina,
		arg.ReduzirAnimacoes,
		arg.ModoTema,
		arg.EstiloTema,
	)
	var i PreferenciasUsuario
	err := row.Scan(
		&i.UsuarioID,
		&i.FormatoData,
		&i.FusoHorario,
		&i.VisualBiblioteca,
		&i.ItensPorPagina,
		&i.ReduzirAnimacoes,
		&i.ModoTema,
		&i.EstiloTema,
		&i.UpdatedAt,
	)
	return i, err
}
