// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssociarJogoZeradoItem(ctx context.Context, arg AssociarJogoZeradoItemParams) (ListaIten, error)
	AtualizarJogoZerado(ctx context.Context, arg AtualizarJogoZeradoParams) (JogosZerado, error)
	AtualizarLista(ctx context.Context, arg AtualizarListaParams) (Lista, error)
	AtualizarPosicaoItem(ctx context.Context, arg AtualizarPosicaoItemParams) error
	AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error
	BuscarCredenciaisUsuarioPorID(ctx context.Context, id int32) (BuscarCredenciaisUsuarioPorIDRow, error)
	BuscarItemPorID(ctx context.Context, arg BuscarItemPorIDParams) (ListaIten, error)
	BuscarJogoPorID(ctx context.Context, arg BuscarJogoPorIDParams) (JogosZerado, error)
	BuscarJogoPorIDParaUpdate(ctx context.Context, arg BuscarJogoPorIDParaUpdateParams) (JogosZerado, error)
	BuscarJogoZeradoDoUsuario(ctx context.Context, arg BuscarJogoZeradoDoUsuarioParams) (BuscarJogoZeradoDoUsuarioRow, error)
	BuscarListaPorID(ctx context.Context, arg BuscarListaPorIDParams) (Lista, error)
	BuscarListaPorIDParaUpdate(ctx context.Context, arg BuscarListaPorIDParaUpdateParams) (Lista, error)
	BuscarSnapshotIGDB(ctx context.Context, chave string) ([]byte, error)
	BuscarTokenResetSenha(ctx context.Context, tokenHash string) (TokensResetSenha, error)
	BuscarUsuarioPorEmail(ctx context.Context, email string) (BuscarUsuarioPorEmailRow, error)
	BuscarUsuarioPorID(ctx context.Context, id int32) (BuscarUsuarioPorIDRow, error)
	ConsumirTokenResetEAtualizarSenha(ctx context.Context, arg ConsumirTokenResetEAtualizarSenhaParams) (int32, error)
	ContarJogosZerados(ctx context.Context, arg ContarJogosZeradosParams) (int64, error)
	CriarItemLista(ctx context.Context, arg CriarItemListaParams) (ListaIten, error)
	CriarJogoZerado(ctx context.Context, arg CriarJogoZeradoParams) (JogosZerado, error)
	CriarLista(ctx context.Context, arg CriarListaParams) (Lista, error)
	CriarTokenResetSenha(ctx context.Context, arg CriarTokenResetSenhaParams) error
	CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error)
	DesassociarJogoZeradoItem(ctx context.Context, arg DesassociarJogoZeradoItemParams) (ListaIten, error)
	DesmarcarGameDoAnoAtual(ctx context.Context, arg DesmarcarGameDoAnoAtualParams) (int32, error)
	DesmarcarGameDoAnoPorID(ctx context.Context, arg DesmarcarGameDoAnoPorIDParams) (int64, error)
	ExcluirItem(ctx context.Context, arg ExcluirItemParams) (int64, error)
	ExcluirJogoZerado(ctx context.Context, arg ExcluirJogoZeradoParams) (int64, error)
	ExcluirLista(ctx context.Context, arg ExcluirListaParams) (int64, error)
	ExisteUsuarioComEmail(ctx context.Context, email string) (bool, error)
	LimparTokensRevogadosExpirados(ctx context.Context) error
	ListarItensPorLista(ctx context.Context, listaID int64) ([]ListaIten, error)
	ListarJogosZerados(ctx context.Context, arg ListarJogosZeradosParams) ([]JogosZerado, error)
	ListarJogosZeradosPorNota(ctx context.Context, arg ListarJogosZeradosPorNotaParams) ([]JogosZerado, error)
	ListarJogosZeradosUsuarioParaMatching(ctx context.Context, usuarioID int32) ([]ListarJogosZeradosUsuarioParaMatchingRow, error)
	ListarListasPorUsuario(ctx context.Context, usuarioID int32) ([]Lista, error)
	ListarRefreshTokensAtivosPorUsuario(ctx context.Context, usuarioID int32) ([]TokensRefreshAtivo, error)
	ListarTodosItensDoUsuario(ctx context.Context, usuarioID int32) ([]ListaIten, error)
	MarcarGameDoAno(ctx context.Context, arg MarcarGameDoAnoParams) (JogosZerado, error)
	ObterAnosUsuario(ctx context.Context, usuarioID int32) ([]int32, error)
	ObterConsolesUsuario(ctx context.Context, usuarioID int32) ([]string, error)
	ObterDetalhesJogoZerado(ctx context.Context, arg ObterDetalhesJogoZeradoParams) (ObterDetalhesJogoZeradoRow, error)
	ObterGenerosUsuario(ctx context.Context, usuarioID int32) ([]pgtype.Text, error)
	ObterMaxPosicaoItem(ctx context.Context, listaID int64) (int32, error)
	ObterResumoGameDoAno(ctx context.Context, usuarioID int32) ([]ObterResumoGameDoAnoRow, error)
	ObterTiposUsuario(ctx context.Context, usuarioID int32) ([]pgtype.Text, error)
	RegistrarRefreshTokenAtivo(ctx context.Context, arg RegistrarRefreshTokenAtivoParams) error
	RegistrarSolicitacaoResetSenha(ctx context.Context, email string) (int16, error)
	RemoverRefreshTokensAtivosPorUsuario(ctx context.Context, usuarioID int32) error
	RevogarToken(ctx context.Context, arg RevogarTokenParams) error
	SalvarSnapshotIGDB(ctx context.Context, arg SalvarSnapshotIGDBParams) error
	TokenEstaRevogado(ctx context.Context, jti string) (bool, error)
}

var _ Querier = (*Queries)(nil)
