// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recuperacao_senha.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarTokenResetSenha = `-- name: BuscarTokenResetSenha :one
SELECT id, usuario_id, token_hash, expira_em, usado_em
FROM tokens_reset_senha
WHERE token_hash = $1
`

func (q *Queries) BuscarTokenResetSenha(ctx context.Context, tokenHash string) (TokensResetSenha, error) {
	row := q.db.QueryRow(ctx, buscarTokenResetSenha, tokenHash)
	var i TokensResetSenha
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.TokenHash,
		&i.ExpiraEm,
		&i.UsadoEm,
	)
	return i, err
}

const consumirTokenResetEAtualizarSenha = `-- name: ConsumirTokenResetEAtualizarSenha :one
WITH token AS (
    UPDATE tokens_reset_senha
    SET usado_em = CURRENT_TIMESTAMP
    WHERE tokens_reset_senha.id = $1
        AND tokens_reset_senha.usado_em IS NULL
        AND tokens_reset_senha.expira_em > CURRENT_TIMESTAMP
    RETURNING usuario_id
), usuario AS (
    UPDATE usuarios
    SET senha_hash = $2
    WHERE usuarios.id = (SELECT usuario_id FROM token)
    RETURNING usuarios.id
)
SELECT usuario.id FROM usuario
`

type ConsumirTokenResetEAtualizarSenhaParams struct {
	ID        int32
	SenhaHash string
}

func (q *Queries) ConsumirTokenResetEAtualizarSenha(ctx context.Context, arg ConsumirTokenResetEAtualizarSenhaParams) (int32, error) {
	row := q.db.QueryRow(ctx, consumirTokenResetEAtualizarSenha, arg.ID, arg.SenhaHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const criarTokenResetSenha = `-- name: CriarTokenResetSenha :exec
INSERT INTO tokens_reset_senha (usuario_id, token_hash, expira_em)
VALUES ($1, $2, $3)
`

type CriarTokenResetSenhaParams struct {
	UsuarioID int32
	TokenHash string
	ExpiraEm  pgtype.Timestamptz
}

func (q *Queries) CriarTokenResetSenha(ctx context.Context, arg CriarTokenResetSenhaParams) error {
	_, err := q.db.Exec(ctx, criarTokenResetSenha, arg.UsuarioID, arg.TokenHash, arg.ExpiraEm)
	return err
}

const listarRefreshTokensAtivosPorUsuario = `-- name: ListarRefreshTokensAtivosPorUsuario :many
SELECT jti, usuario_id, expira_em
FROM tokens_refresh_ativos
WHERE usuario_id = $1 AND expira_em > CURRENT_TIMESTAMP
`

func (q *Queries) ListarRefreshTokensAtivosPorUsuario(ctx context.Context, usuarioID int32) ([]TokensRefreshAtivo, error) {
	rows, err := q.db.Query(ctx, listarRefreshTokensAtivosPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokensRefreshAtivo
	for rows.Next() {
		var i TokensRefreshAtivo
		if err := rows.Scan(&i.Jti, &i.UsuarioID, &i.ExpiraEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarRefreshTokenAtivo = `-- name: RegistrarRefreshTokenAtivo :exec
INSERT INTO tokens_refresh_ativos (jti, usuario_id, expira_em)
VALUES ($1, $2, $3)
ON CONFLICT (jti) DO NOTHING
`

type RegistrarRefreshTokenAtivoParams struct {
	Jti       string
	UsuarioID int32
	ExpiraEm  pgtype.Timestamptz
}

func (q *Queries) RegistrarRefreshTokenAtivo(ctx context.Context, arg RegistrarRefreshTokenAtivoParams) error {
	_, err := q.db.Exec(ctx, registrarRefreshTokenAtivo, arg.Jti, arg.UsuarioID, arg.ExpiraEm)
	return err
}

const registrarSolicitacaoResetSenha = `-- name: RegistrarSolicitacaoResetSenha :one
INSERT INTO limites_solicitacao_reset_senha (email, janela_iniciada_em, quantidade)
VALUES ($1, CURRENT_TIMESTAMP, 1)
ON CONFLICT (email) DO UPDATE
SET
    janela_iniciada_em = CASE
        WHEN limites_solicitacao_reset_senha.janela_iniciada_em <= CURRENT_TIMESTAMP - INTERVAL '1 hour' THEN CURRENT_TIMESTAMP
        ELSE limites_solicitacao_reset_senha.janela_iniciada_em
    END,
    quantidade = CASE
        WHEN limites_solicitacao_reset_senha.janela_iniciada_em <= CURRENT_TIMESTAMP - INTERVAL '1 hour' THEN 1
        ELSE limites_solicitacao_reset_senha.quantidade + 1
    END
WHERE
    limites_solicitacao_reset_senha.janela_iniciada_em <= CURRENT_TIMESTAMP - INTERVAL '1 hour'
    OR limites_solicitacao_reset_senha.quantidade < 3
RETURNING quantidade
`

func (q *Queries) RegistrarSolicitacaoResetSenha(ctx context.Context, email string) (int16, error) {
	row := q.db.QueryRow(ctx, registrarSolicitacaoResetSenha, email)
	var quantidade int16
	err := row.Scan(&quantidade)
	return quantidade, err
}

const removerRefreshTokensAtivosPorUsuario = `-- name: RemoverRefreshTokensAtivosPorUsuario :exec
DELETE FROM tokens_refresh_ativos WHERE usuario_id = $1
`

func (q *Queries) RemoverRefreshTokensAtivosPorUsuario(ctx context.Context, usuarioID int32) error {
	_, err := q.db.Exec(ctx, removerRefreshTokensAtivosPorUsuario, usuarioID)
	return err
}
