// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tokens_revogados.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const limparTokensRevogadosExpirados = `-- name: LimparTokensRevogadosExpirados :exec
DELETE FROM tokens_revogados WHERE expira_em <= CURRENT_TIMESTAMP
`

func (q *Queries) LimparTokensRevogadosExpirados(ctx context.Context) error {
	_, err := q.db.Exec(ctx, limparTokensRevogadosExpirados)
	return err
}

const revogarToken = `-- name: RevogarToken :exec
INSERT INTO tokens_revogados (jti, expira_em)
VALUES ($1, $2)
ON CONFLICT (jti) DO NOTHING
`

type RevogarTokenParams struct {
	Jti      string
	ExpiraEm pgtype.Timestamptz
}

func (q *Queries) RevogarToken(ctx context.Context, arg RevogarTokenParams) error {
	_, err := q.db.Exec(ctx, revogarToken, arg.Jti, arg.ExpiraEm)
	return err
}

const tokenEstaRevogado = `-- name: TokenEstaRevogado :one
SELECT EXISTS(SELECT 1 FROM tokens_revogados WHERE jti = $1)
`

func (q *Queries) TokenEstaRevogado(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, tokenEstaRevogado, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
