// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarPerfilUsuario = `-- name: AtualizarPerfilUsuario :execrows
UPDATE usuarios
SET
    nome = $2,
    username = $3,
    bio = $4,
    jogo_favorito_id = $5,
    console_favorito = $6,
    jogando_desde = $7
WHERE id = $1
`

type AtualizarPerfilUsuarioParams struct {
	ID              int32
	Nome            string
	Username        pgtype.Text
	Bio             pgtype.Text
	JogoFavoritoID  pgtype.Int4
	ConsoleFavorito pgtype.Text
	JogandoDesde    pgtype.Int2
}

func (q *Queries) AtualizarPerfilUsuario(ctx context.Context, arg AtualizarPerfilUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, atualizarPerfilUsuario,
		arg.ID,
		arg.Nome,
		arg.Username,
		arg.Bio,
		arg.JogoFavoritoID,
		arg.ConsoleFavorito,
		arg.JogandoDesde,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const atualizarSenhaUsuario = `-- name: AtualizarSenhaUsuario :exec
UPDATE usuarios
SET senha_hash = $2
WHERE id = $1
`

type AtualizarSenhaUsuarioParams struct {
	ID        int32
	SenhaHash string
}

func (q *Queries) AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error {
	_, err := q.db.Exec(ctx, atualizarSenhaUsuario, arg.ID, arg.SenhaHash)
	return err
}

const buscarCredenciaisUsuarioPorID = `-- name: BuscarCredenciaisUsuarioPorID :one
SELECT id, nome, email, senha_hash, username, avatar_url, bio, idioma, created_at
FROM usuarios
WHERE id = $1
`

type BuscarCredenciaisUsuarioPorIDRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) BuscarCredenciaisUsuarioPorID(ctx context.Context, id int32) (BuscarCredenciaisUsuarioPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarCredenciaisUsuarioPorID, id)
	var i BuscarCredenciaisUsuarioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const buscarPerfilCompletoPorID = `-- name: BuscarPerfilCompletoPorID :one
SELECT
    u.id,
    u.nome,
    u.email,
    u.username,
    u.avatar_url,
    u.bio,
    u.jogo_favorito_id,
    u.console_favorito,
    u.jogando_desde,
    j.id AS fav_id,
    j.nome AS fav_nome,
    j.igdb_capa_url AS fav_capa_url,
    COALESCE((
        SELECT EXTRACT(YEAR FROM MIN(finalizado_em))::int
        FROM jogos_zerados
        WHERE usuario_id = u.id AND deleted_at IS NULL
    ), 0)::int AS primeiro_ano_zerado
FROM usuarios u
LEFT JOIN jogos_zerados j ON j.id = u.jogo_favorito_id AND j.usuario_id = u.id AND j.deleted_at IS NULL
WHERE u.id = $1
`

type BuscarPerfilCompletoPorIDRow struct {
	ID                int32
	Nome              string
	Email             string
	Username          pgtype.Text
	AvatarUrl         pgtype.Text
	Bio               pgtype.Text
	JogoFavoritoID    pgtype.Int4
	ConsoleFavorito   pgtype.Text
	JogandoDesde      pgtype.Int2
	FavID             pgtype.Int4
	FavNome           pgtype.Text
	FavCapaUrl        pgtype.Text
	PrimeiroAnoZerado int32
}

func (q *Queries) BuscarPerfilCompletoPorID(ctx context.Context, id int32) (BuscarPerfilCompletoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarPerfilCompletoPorID, id)
	var i BuscarPerfilCompletoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.JogoFavoritoID,
		&i.ConsoleFavorito,
		&i.JogandoDesde,
		&i.FavID,
		&i.FavNome,
		&i.FavCapaUrl,
		&i.PrimeiroAnoZerado,
	)
	return i, err
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, nome, email, senha_hash, username, avatar_url, bio, idioma, created_at
FROM usuarios
WHERE email = $1
`

type BuscarUsuarioPorEmailRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (BuscarUsuarioPorEmailRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, email)
	var i BuscarUsuarioPorEmailRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :one
SELECT id, nome, email, idioma, created_at
FROM usuarios
WHERE id = $1
`

type BuscarUsuarioPorIDRow struct {
	ID        int32
	Nome      string
	Email     string
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id int32) (BuscarUsuarioPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorID, id)
	var i BuscarUsuarioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const criarUsuario = `-- name: CriarUsuario :one
INSERT INTO usuarios (
    nome,
    email,
    senha_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, nome, email, username, avatar_url, bio, idioma, created_at
`

type CriarUsuarioParams struct {
	Nome      string
	Email     string
	SenhaHash string
}

type CriarUsuarioRow struct {
	ID        int32
	Nome      string
	Email     string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, criarUsuario, arg.Nome, arg.Email, arg.SenhaHash)
	var i CriarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const existeJogoZeradoDoUsuario = `-- name: ExisteJogoZeradoDoUsuario :one
SELECT EXISTS(
    SELECT 1 FROM jogos_zerados
    WHERE id = $1 AND usuario_id = $2 AND deleted_at IS NULL
)
`

type ExisteJogoZeradoDoUsuarioParams struct {
	ID        int32
	UsuarioID int32
}

func (q *Queries) ExisteJogoZeradoDoUsuario(ctx context.Context, arg ExisteJogoZeradoDoUsuarioParams) (bool, error) {
	row := q.db.QueryRow(ctx, existeJogoZeradoDoUsuario, arg.ID, arg.UsuarioID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existeUsuarioComEmail = `-- name: ExisteUsuarioComEmail :one
SELECT EXISTS(
    SELECT 1 FROM usuarios WHERE email = $1
)
`

func (q *Queries) ExisteUsuarioComEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existeUsuarioComEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
