// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: usuarios.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarSenhaUsuario = `-- name: AtualizarSenhaUsuario :exec
UPDATE usuarios
SET senha_hash = $2
WHERE id = $1
`

type AtualizarSenhaUsuarioParams struct {
	ID        int32
	SenhaHash string
}

func (q *Queries) AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error {
	_, err := q.db.Exec(ctx, atualizarSenhaUsuario, arg.ID, arg.SenhaHash)
	return err
}

const buscarCredenciaisUsuarioPorID = `-- name: BuscarCredenciaisUsuarioPorID :one
SELECT id, nome, email, senha_hash, username, avatar_url, bio, idioma, created_at
FROM usuarios
WHERE id = $1
`

type BuscarCredenciaisUsuarioPorIDRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) BuscarCredenciaisUsuarioPorID(ctx context.Context, id int32) (BuscarCredenciaisUsuarioPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarCredenciaisUsuarioPorID, id)
	var i BuscarCredenciaisUsuarioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, nome, email, senha_hash, username, avatar_url, bio, idioma, created_at
FROM usuarios
WHERE email = $1
`

type BuscarUsuarioPorEmailRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (BuscarUsuarioPorEmailRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, email)
	var i BuscarUsuarioPorEmailRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :one
SELECT id, nome, email, idioma, created_at
FROM usuarios
WHERE id = $1
`

type BuscarUsuarioPorIDRow struct {
	ID        int32
	Nome      string
	Email     string
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id int32) (BuscarUsuarioPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorID, id)
	var i BuscarUsuarioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const criarUsuario = `-- name: CriarUsuario :one
INSERT INTO usuarios (
    nome,
    email,
    senha_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, nome, email, username, avatar_url, bio, idioma, created_at
`

type CriarUsuarioParams struct {
	Nome      string
	Email     string
	SenhaHash string
}

type CriarUsuarioRow struct {
	ID        int32
	Nome      string
	Email     string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	Idioma    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, criarUsuario, arg.Nome, arg.Email, arg.SenhaHash)
	var i CriarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Idioma,
		&i.CreatedAt,
	)
	return i, err
}

const existeUsuarioComEmail = `-- name: ExisteUsuarioComEmail :one
SELECT EXISTS(
    SELECT 1 FROM usuarios WHERE email = $1
)
`

func (q *Queries) ExisteUsuarioComEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existeUsuarioComEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
